name: anime_app
description: A flutter anime watch app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.9+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  anitube_crawler_api:
    git:
      url: git@github.com:sc4v3ng3r/anitube_crawler_api.git
      ref: 5d8b5345141d24645326fe9c42ca8fd9d8563bca

  provider: ^3.1.0
  flutter_advanced_networkimage: ^0.7.0
  video_player: ^0.10.8
    # This is the old version hosted in my github. Used when needed http headers values. 
    #git:
    #  url: git@github.com:sc4v3ng3r/flutter-plugins.git
    #  ref: eedec50bbc65374ed322c38ae729bc6f306f1a71
    #  path: packages/video_player
      
  build_runner: ^1.7.2
  carousel_pro: ^1.0.0
  wakelock: ^0.1.3+3
  palette_generator: ^0.2.0
  random_color: ^1.0.3
  sqflite: ^1.1.7+1
  path: ^1.6.4
  bot_toast: ^2.1.0
  flutter_svg: ^0.17.1
  mobx: ^0.3.9+3
  flutter_mobx: ^0.3.3+3
  mobx_codegen: ^0.3.10+1
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  intl_translation: ^0.17.7
  intl: ^0.16.0
  package_info: ^0.4.0+13

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any  
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/font/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Black.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Regular.ttf

